# Generated by Django 3.1.4 on 2021-01-12 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malt', '0003_auto_20210104_2256'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fileasset',
            name='fileasset_unique',
        ),
        migrations.RemoveConstraint(
            model_name='folderasset',
            name='folderasset_unique',
        ),
        migrations.AddField(
            model_name='fileasset',
            name='trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folderasset',
            name='trashed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='fileasset',
            constraint=models.UniqueConstraint(condition=models.Q(trashed=False), fields=('user', 'parent', 'name', 'trashed'), name='fileasset_unique_with_parent'),
        ),
        migrations.AddConstraint(
            model_name='fileasset',
            constraint=models.UniqueConstraint(condition=models.Q(('parent', None), ('trashed', False)), fields=('user', 'name', 'trashed'), name='fileasset_unique_without_parent'),
        ),
        migrations.AddConstraint(
            model_name='folderasset',
            constraint=models.UniqueConstraint(condition=models.Q(trashed=False), fields=('user', 'parent', 'name', 'trashed'), name='folderasset_unique_with_parent'),
        ),
        migrations.AddConstraint(
            model_name='folderasset',
            constraint=models.UniqueConstraint(condition=models.Q(('parent', None), ('trashed', False)), fields=('user', 'name', 'trashed'), name='folderasset_unique_without_parent'),
        ),
    ]
